### ISSUE TITLE
Post-Mortem on #199

### ISSUE THREAD

**Issue by daviddias** [ipfs-inactive/old-js-ipfs-website#208]
@PedroMiguelSS @vasco-santos @alanshaw can you run a (one page, doesn't need to be longer) post mortem on https://github.com/ipfs/js.ipfs.io/issues/199?

**Comment by PedroMiguelSS** [comment]
I did produce [this document](https://docs.google.com/document/d/12mSdTN_SGlTYFu01AQtPO17MN-tI68V6I9GtRWrOSyg/edit?usp=sharing) for now. It must be reviewed and @vasco-santos is on it.
