### ISSUE TITLE
Suggestion: use ipfs.get instead of ipfs.cat in examples

### ISSUE THREAD

**Issue by alanshaw** [ipfs-inactive/old-js-ipfs-website#234]
To new programmers `cat` means only 😸 and is confusing.

**Comment by terichadbourne** [comment]
I did discover some differences between `get` and `cat` with help from @alanshaw while exploring the docs, but I agree that `cat` didn't mean anything to me intuitively in the way `get` does. (I was also coming from having learned `put` and `get in the DAG API.)
