### ISSUE TITLE
Suggestion: more explanation for examples in "What you can build with JS-IPFS"

### ISSUE THREAD

**Issue by alanshaw** [ipfs-inactive/old-js-ipfs-website#235]
"Browser video" streaming is simple enough, but the rendered page should give some information about what is happening.

"Exchange files" - so much code, zero explanation...it's such a great demo but it needs to walk the user through what's there in some way (refs https://github.com/ipfs/js.ipfs.io/issues/224).

**Comment by terichadbourne** [comment]
I'd find it really helpful to see a link from that exchange files app example on the main website to the tutorial about how it's built at https://github.com/ipfs/js-ipfs/tree/master/examples/exchange-files-in-browser
