### ISSUE TITLE
Service Worker Gateway activation message not showing for mobile and small screen situations

### ISSUE THREAD

**Issue by voidao** [ipfs-inactive/old-js-ipfs-website#253]
<img width="426" alt="Screen Shot 2019-03-25 at 12 30 40 PM" src="https://user-images.githubusercontent.com/23121736/54895297-e22e0200-4ef9-11e9-91c2-4385611e216f.png">

**Comment by HenryFMa** [comment]
Could simple make the message always showing as:
`.message {
    position: absolute;
    top: 50%;
    width: 50%;
...`

But pretty sure it should not be the best solution.

**Comment by PedroMiguelSS** [comment]
You're right @HenryFMa. I'll take a look asap to solve this. 

Thank you! 🙏
