### ISSUE TITLE
Better highlight ProtoSchool tutorials from js.ipfs.io 

### ISSUE THREAD

**Issue by terichadbourne** [ipfs-inactive/old-js-ipfs-website#286]
@achingbrain @johnnymatthews 

Currently we have a small text link to ProtoSchool tutorials under "Getting Started" (I'm trying to open a PR for an update that leads to the new IPFS course instead of all ProtoSchool content from this link but your commit proofer bot hates me). 

![image](https://user-images.githubusercontent.com/19171465/87337719-e37da680-c511-11ea-98a4-0827d3aac522.png)

However, the more obvious Tutorials callout in the nav goes to [this GitHub folder](https://github.com/ipfs/js-ipfs/tree/master/examples#js-ipfs-examples-and-tutorials), so we're missing the opportunity to draw attention to a variety of carefully crafted tutorials that the IPFS team has worked with the ProtoSchool team to create: 

![image](https://user-images.githubusercontent.com/19171465/87338048-79b1cc80-c512-11ea-81c2-90cf632e0b71.png)

Are all of the examples in that GitHub folder in active maintenance? If you still like this as a place for Tutorials to direct to, shall I add a markdown file there that takes people to the IPFS tutorials on ProtoSchool (all of which are based on js-ipfs)?  

Other suggestions that are more user-friendly?

**Comment by terichadbourne** [comment]
See #287 for the PR mentioned above (doesn't fix the issue asked about here).

**Comment by johnnymatthews** [comment]
The examples in that folder are getting fleshed out and migrated into `docs.ipfs.io` this quarter, so you can link to there once that's all done. Not sure how often they get updated, but I'm assuming whenever breaking changes go into IPFS that affect the examples.
