### ISSUE TITLE
Build is broken with node:lts  / update dependencies

### ISSUE THREAD

**Issue by juliangruber** [ipfs-inactive/old-js-ipfs-website#310]
`npm ci` fails on node 12-16 on macOS because of the `sharp` dependency.

**Comment by lidel** [comment]
Since cache got purged on CI, we also fail on Node 10:
https://app.fleek.co/#/sites/js-ipfs-website/deploys/2022-08-04T00:27:18.888Z?accountId=protocollabs-team
