### ISSUE TITLE
Update in light of Helia release and js-ipfs deprecation

### ISSUE THREAD

**Issue by BigLep** [ipfs-inactive/old-js-ipfs-website#316]
# Problems to solve
js.ipfs.tech is outdated and not maintained in that it is pointing to js-ipfs which is deprecated per https://github.com/ipfs/js-ipfs/issues/4336

Specific actions we need to take as a result:
1. Remove inaccurate information (particularly references to js-ipfs which is now deprecated)
2. Surface newer/better IPFS in JS options like Helia.

# What's the purpose of this website?
@BigLep believes it is:
1. Have a polished statement that IPFS takes (or at least wants to take) JS seriously.  We should give the sense that there is more behind this effort than a couple of rogue hackers. 
2. Succinctly describe the options available to someone who wants to do IPFS with JS and link to where they can link more.

# Notes
Principles I think we should apply when working on this:
1. It's better to have less information than inaccurate information.
2. We should feel at liberty to strip out functionality.  For example, if we can't handle translations right now, lets remove them.  
3. Avoid duplication information.  If there is content that belongs elsewhere (e.g., docs.ipfs.tech, Helia project docs/wiki), lets link there.
4. If we are going to squat on js.ipfs.tech, we should be multiple implementation aware.  Helia is obviously an important part of the story, but there are other ways to engage with IPFS in JS than Helia (e.g., js-kubo-rpc-client).  Alternatively, we could convert this to helia.ipfs.tech (or something similar) and can make it as Helia-specific as we want.
5. We should bias towards more "timeless" information.  We don't want this to be a place that requires frequent updates because that won't happen with current staffing.

**Comment by lidel** [comment]
https://github.com/ipfs-inactive/old-js-ipfs-website/pull/320 deprecated this website and domain now redirects to JS docs on our docs website. I'm closing all issues and archiving:  #321
