### ISSUE TITLE
React-intl: should react components be used?

### ISSUE THREAD

**Issue by PedroMiguelSS** [ipfs-inactive/old-js-ipfs-website#87]
Should (react-intl) react components be used instead of accessing messages directly? Should we always use [FormattedMessage](https://github.com/yahoo/react-intl/wiki/Components#formattedmessage) component?

Disadvantages of this approach: a wrapper div is always automatically created.

**Comment by satazor** [comment]
I would use the react components for several reasons:

- Performance
- Usage with placeholders; using `formatMessage` directly is hacky
- No more `injectIntl` is necessary

It seems that a wrapper is no longer necessary:

```jsx
<FormattedMessage id=“hero.foo”>{ (txt) => txt }</FormattedMessage>
``
`

should work.. or

```jsx
<FormattedMessage id=“hero.foo”>{ (txt) => <Fragment>{ txt }</Fragment> }</FormattedMessage>
```

The later is more verbose, but we can create our own `FormattedMessage` that does that!

**Comment by daviddias** [comment]
Is this issue still relevant?
